### ISSUE TITLE
Bag

### ISSUE THREAD

**Issue by MIHUTKA3** [itayzit/openai-async#1]
urllib.request.urlretrieve(response.json()["data"][0]["url"], "mihutkachatgpt_bot.jpg") KeyError: 'data'

```
            response = await openai_async.generate_img(
                "token",
                timeout=10,
                payload={
                    "prompt": message.text,
                    "n": 1,
                    "size": "1024x1024"
                },
            )
            urllib.request.urlretrieve(response.json()["data"][0]["url"], "mihutkachatgpt_bot.jpg")
            photo = open('mihutkachatgpt_bot.jpg', 'rb')
            await bot.send_photo(message.from_user.id, photo)
```

**Comment by itayzit** [comment]
Hey, are you sure you got a good response?
I mean, what is the status code you got for the response? (should be 200)


The code you pasted here works for me.

**Comment by Arse4ek** [comment]
> Hey, are you sure you got a good response? I mean, what is the status code you got for the response? (should be 200)
> 
> The code you pasted here works for me.
![image](https://user-images.githubusercontent.com/74795614/217512506-c5ec6315-c891-44ad-ac9c-dd3defd38072.png)
I use this, but it not work

**Comment by Arse4ek** [comment]
> Hey, are you sure you got a good response? I mean, what is the status code you got for the response? (should be 200)
> 
> The code you pasted here works for me.

ok, how do I do async photo generation?

**Comment by Arse4ek** [comment]
> Hey, are you sure you got a good response? I mean, what is the status code you got for the response? (should be 200)
> 
> The code you pasted here works for me.

![image](https://user-images.githubusercontent.com/74795614/217543831-bb730ccc-48aa-4bfb-8668-d83751bee0b3.png)

**Comment by MIHUTKA3** [comment]
> Hey, are you sure you got a good response? I mean, what is the status code you got for the response? (should be 200)
> 
> The code you pasted here works for me.

i fix, thanks

**Comment by itayzit** [comment]
great :)
