### ISSUE TITLE
New to Async. Can this send multiple prompts at a time?

### ISSUE THREAD

**Issue by ibehnam** [itayzit/openai-async#3]
Sorry for the noob question. I couldn't get OpenAI's `acreate` method of Async work. So I found your package, but I don't know how this can be used to make `N` requests to the API at once, and stay below the rate limit. Can you please explain this?

**Comment by taziksh** [comment]
Yes, how is this different from OpenAI's official Python wrapper's `acreate()`?
https://github.com/openai/openai-python/pull/146

**Comment by itayzit** [comment]
hey @taziksh this is not different, it just uses requests and asyncio instead of their native support. i developed it before they had native support for async 😄
